//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPickerConfig) DeepCopyInto(out *EndpointPickerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SchedulingProfiles != nil {
		in, out := &in.SchedulingProfiles, &out.SchedulingProfiles
		*out = make([]SchedulingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(FeatureGates, len(*in))
		copy(*out, *in)
	}
	if in.SaturationSignalRecorder != nil {
		in, out := &in.SaturationSignalRecorder, &out.SaturationSignalRecorder
		*out = new(SaturationSignalRecorder)
		(*in).DeepCopyInto(*out)
	}
	if in.SaturationController != nil {
		in, out := &in.SaturationController, &out.SaturationController
		*out = new(SaturationController)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPickerConfig.
func (in *EndpointPickerConfig) DeepCopy() *EndpointPickerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointPickerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointPickerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FeatureGates) DeepCopyInto(out *FeatureGates) {
	{
		in := &in
		*out = make(FeatureGates, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGates.
func (in FeatureGates) DeepCopy() FeatureGates {
	if in == nil {
		return nil
	}
	out := new(FeatureGates)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginSpec) DeepCopyInto(out *PluginSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSpec.
func (in *PluginSpec) DeepCopy() *PluginSpec {
	if in == nil {
		return nil
	}
	out := new(PluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaturationController) DeepCopyInto(out *SaturationController) {
	*out = *in
	if in.SaturationSetpoint != nil {
		in, out := &in.SaturationSetpoint, &out.SaturationSetpoint
		*out = new(float64)
		**out = **in
	}
	if in.SaturationHeadroom != nil {
		in, out := &in.SaturationHeadroom, &out.SaturationHeadroom
		*out = new(float64)
		**out = **in
	}
	if in.ProportionalGain != nil {
		in, out := &in.ProportionalGain, &out.ProportionalGain
		*out = new(float64)
		**out = **in
	}
	if in.MinDispatchRate != nil {
		in, out := &in.MinDispatchRate, &out.MinDispatchRate
		*out = new(float64)
		**out = **in
	}
	if in.MaxQueueLatency != nil {
		in, out := &in.MaxQueueLatency, &out.MaxQueueLatency
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EffectiveBatchAlpha != nil {
		in, out := &in.EffectiveBatchAlpha, &out.EffectiveBatchAlpha
		*out = new(float64)
		**out = **in
	}
	if in.QueueDepthAlpha != nil {
		in, out := &in.QueueDepthAlpha, &out.QueueDepthAlpha
		*out = new(float64)
		**out = **in
	}
	if in.ServiceRateWindow != nil {
		in, out := &in.ServiceRateWindow, &out.ServiceRateWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeakInflightConcurrencyWindow != nil {
		in, out := &in.PeakInflightConcurrencyWindow, &out.PeakInflightConcurrencyWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeakInflightConcurrencySamples != nil {
		in, out := &in.PeakInflightConcurrencySamples, &out.PeakInflightConcurrencySamples
		*out = new(int)
		**out = **in
	}
	if in.KVCacheWindow != nil {
		in, out := &in.KVCacheWindow, &out.KVCacheWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KVCacheSamples != nil {
		in, out := &in.KVCacheSamples, &out.KVCacheSamples
		*out = new(int)
		**out = **in
	}
	if in.MaturityQuorumPercentage != nil {
		in, out := &in.MaturityQuorumPercentage, &out.MaturityQuorumPercentage
		*out = new(float64)
		**out = **in
	}
	if in.DormantTimeout != nil {
		in, out := &in.DormantTimeout, &out.DormantTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MetricsStalenessThreshold != nil {
		in, out := &in.MetricsStalenessThreshold, &out.MetricsStalenessThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinSamplesForEffectiveBatchMaturity != nil {
		in, out := &in.MinSamplesForEffectiveBatchMaturity, &out.MinSamplesForEffectiveBatchMaturity
		*out = new(uint64)
		**out = **in
	}
	if in.MinEffectiveCountForServiceRateMaturity != nil {
		in, out := &in.MinEffectiveCountForServiceRateMaturity, &out.MinEffectiveCountForServiceRateMaturity
		*out = new(float64)
		**out = **in
	}
	if in.MinBatchSampleInterval != nil {
		in, out := &in.MinBatchSampleInterval, &out.MinBatchSampleInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaturationController.
func (in *SaturationController) DeepCopy() *SaturationController {
	if in == nil {
		return nil
	}
	out := new(SaturationController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaturationSignalRecorder) DeepCopyInto(out *SaturationSignalRecorder) {
	*out = *in
	if in.TickInterval != nil {
		in, out := &in.TickInterval, &out.TickInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxExpectedCompletionsQPS != nil {
		in, out := &in.MaxExpectedCompletionsQPS, &out.MaxExpectedCompletionsQPS
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaturationSignalRecorder.
func (in *SaturationSignalRecorder) DeepCopy() *SaturationSignalRecorder {
	if in == nil {
		return nil
	}
	out := new(SaturationSignalRecorder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingPlugin) DeepCopyInto(out *SchedulingPlugin) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingPlugin.
func (in *SchedulingPlugin) DeepCopy() *SchedulingPlugin {
	if in == nil {
		return nil
	}
	out := new(SchedulingPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingProfile) DeepCopyInto(out *SchedulingProfile) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]SchedulingPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingProfile.
func (in *SchedulingProfile) DeepCopy() *SchedulingProfile {
	if in == nil {
		return nil
	}
	out := new(SchedulingProfile)
	in.DeepCopyInto(out)
	return out
}
